### ISSUE TITLE
Sponsors Section

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/Apoorv#10]
# Expected Behavior
The Section should look like this

![image](https://user-images.githubusercontent.com/54381338/214288334-510d958a-a7c7-4869-9fa9-835f0e623e62.png)

## Context

You Can take a look at this Figma file [here](https://www.figma.com/file/89qeATFJBFmyltCq8oiGCs/website-(Copy)?node-id=0%3A1&t=Ci28JnaZ5c4QfPCI-1)

**Comment by bhavyag54** [comment]
done
