### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/Apoorv#11]
# Expected Behavior
The Section should look like this

![image](https://user-images.githubusercontent.com/54381338/214288534-de3f514e-96b9-4b91-b9e7-d8946ccc8bb0.png)

## Context

You Can take a look at this Figma file [here](https://www.figma.com/file/89qeATFJBFmyltCq8oiGCs/website-(Copy)?node-id=0%3A1&t=Ci28JnaZ5c4QfPCI-1)

**Comment by Aditya-Shitale** [comment]
I want to take this issue.

**Comment by shashank1503-cipher** [comment]
Assigned @Aditya-Shitale
