### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/Apoorv#6]
# Expected Behavior

The Section should look like this

![image](https://user-images.githubusercontent.com/54381338/214286010-ec40a7ec-6c17-4d28-9777-b8707cd91171.png)

## Context

You Can take a look at this Figma file [here](https://www.figma.com/file/89qeATFJBFmyltCq8oiGCs/website-(Copy)?node-id=0%3A1&t=Ci28JnaZ5c4QfPCI-1)

**Comment by shiv12131** [comment]
i would like to work in this issue

**Comment by shashank1503-cipher** [comment]
Assigned to you @shiv12131

**Comment by 1-aditya-2** [comment]
i would also like to work along with @shiv12131

**Comment by shashank1503-cipher** [comment]
Assigned to you as well @1-aditya-2
