### ISSUE TITLE
Description Section

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/Apoorv#7]
# Expected Behavior

The Section should look like this

![image](https://user-images.githubusercontent.com/54381338/214286373-34020c42-584b-4684-8c55-71e2f460b3ba.png)

## Context

You Can take a look at this Figma file [here](https://www.figma.com/file/89qeATFJBFmyltCq8oiGCs/website-(Copy)?node-id=0%3A1&t=Ci28JnaZ5c4QfPCI-1)

**Comment by 1-aditya-2** [comment]
I would like to work on this issue.

**Comment by shashank1503-cipher** [comment]
Assigned to you @1-aditya-2
