### ISSUE TITLE
Speaker Section

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/Apoorv#9]
# Expected Behavior
The Section should look like this

![image](https://user-images.githubusercontent.com/54381338/214287715-c90f8dec-47e0-46a3-bc8a-c0bbad34d045.png)

## Context

You Can take a look at this Figma file [here](https://www.figma.com/file/89qeATFJBFmyltCq8oiGCs/website-(Copy)?node-id=0%3A1&t=Ci28JnaZ5c4QfPCI-1)

**Comment by Tanujkarteek** [comment]
I would like to work on this

**Comment by shashank1503-cipher** [comment]
Assigned to you @Tanujkarteek

**Comment by Omkar1622** [comment]
I would like to work on this issue
